/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XRay {
    }
}
declare global {
    interface HTMLXRayElement extends Components.XRay, HTMLStencilElement {
    }
    var HTMLXRayElement: {
        prototype: HTMLXRayElement;
        new (): HTMLXRayElement;
    };
    interface HTMLElementTagNameMap {
        "x-ray": HTMLXRayElement;
    }
}
declare namespace LocalJSX {
    interface XRay {
    }
    interface IntrinsicElements {
        "x-ray": XRay;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "x-ray": LocalJSX.XRay & JSXBase.HTMLAttributes<HTMLXRayElement>;
        }
    }
}
